account_id = "ac29ce961091a45f22b60d762e3e33a8"
name = "durable-rpc"
compatibility_date = "2024-04-05"
workers_dev = false
main = "./src/index.ts"
routes = [
  'test.com',
  'test.com/*'
]

[durable_objects]
bindings = [
  { name = "Counter", class_name = "Counter" },
]

[[migrations]]
tag = "v1"
new_classes = ["Counter"]
